version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5-stretch
    steps:
      - checkout
      - run: ls
      - run: python -m venv env
      - run: env/bin/python -m unittest discover petutils -p "*.py"
